[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc", "cp -r src/public dist/public", "cp -r src/idl dist/idl"]

[start]
cmd = "npx prisma migrate deploy && node dist/index.js"
